# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Scott Dorman'
tagline:          'Microsoft MVP, Software Architect, Developer, Author'
description:      ''
baseurl:          http://scottdorman.github.io/

author:
  name:           'Scott Dorman'
  url:            https://twitter.com/sdorman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scottdorman/scottdorman.github.io
